// House-specific data for the Route Checklist.
//
// Each house entry:
//   name      — house name shown in the sidebar picker (must be unique)
//   equipment — flags for gear the house may or may not have.
//               false  = house does NOT have it → related checklist items hide.
//               true / missing = shown as normal.
//               Flags used: generator, roofCoils, sumpPump, garbageDisposal,
//                           frontLoadWashers, airExchanger, waterSoftener
//   notes     — house-specific detail shown inline under the matching
//               checklist item. Keys: fireExtinguishers, furnaceFilter,
//               fridgeCoils, waterSoftener, shutoffs, knives, medLock,
//               atticAccess, dryerVents
//   info      — [label, detail] pairs with no checklist item; shown in the
//               sidebar "House info" panel.
//
// Door/entry codes are NOT stored here — they live in house-codes.local.js,
// which stays on the device and is never committed (see .gitignore).
const HOUSES = [
  {
    name: "Dogwood",
    equipment: {
      roofCoils: true,
      airExchanger: true,
      frontLoadWashers: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): laundry closet · RS (down): mech room · Garage: by main door · One in the van",
      furnaceFilter: "20x25x20",
      fridgeCoils: "Residents (up): front · RS (down): back",
      waterSoftener: "In the mechanical room",
      shutoffs: "Gas & water: mech room. Outside water: mech room above softener + under RS kitchen sink",
      knives: "Block on counter",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: hallway by bathroom",
      dryerVents: "Residents (up): NW side · RS (down): NE side under deck",
    },
    info: [
      ["Paint", "Laundry closet"],
      ["Fuse box", "Garage by MTX cabinet"],
      ["Attic access", "Hallway by bathroom"],
    ],
  },
  {
    name: "Roselawn",
    equipment: {
      generator: true,
      waterSoftener: true,
      sumpPump: false,
      roofCoils: false,
      garbageDisposal: false,
      frontLoadWashers: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): kitchen sink, van, garage · RS (down): kitchen sink",
      furnaceFilter: "16x25x1 — change monthly",
      shutoffs: "Main water: mech room by washing machine. Main gas: mech room by furnace. Outside: behind back-yard faucet in wall + mech room above softener",
      medLock: "Magnet and key",
      atticAccess: "Attic access: big closet in dining area",
    },
    info: [
      ["Paint", "Storage room by RS kitchen"],
      ["MTX cabinet", "Garage"],
      ["Jacuzzi tub cover", "Velcro"],
      ["Humidifier", "Mech room"],
      ["Med lock", "Magnet and key"],
      ["Attic access", "Big closet in dining area"],
    ],
  },
  {
    name: "140th Lane East",
    equipment: {
      waterSoftener: true,
      airExchanger: true,
      garbageDisposal: false,
      frontLoadWashers: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): back hall by the pantry · RS (down): storage room off the kitchen, right around the corner",
      furnaceFilter: "16x25x1",
      fridgeCoils: "Residents (up): front of fridge · RS (down): front of fridge",
      waterSoftener: "In the mechanical room",
      shutoffs: "Main water: mech room by the water softener. Main gas: mech room on the furnace. Outside water: one in mech room (labeled) + one storage room, east wall, next to kitchen (labeled)",
      knives: "Second drawer down next to the dishwasher",
      medLock: "Key access",
      atticAccess: "Attic access: east bedroom",
    },
    info: [
      ["Paint", "Pantry in the hallway to the garage; mech room bottom of wire shelf. CALL SUSIE BEFORE PAINTING."],
      ["MTX cabinet", "Garage"],
      ["Breaker box", "Mechanical room"],
      ["Van key", "Entryway by the garage, in the closet with the van bag"],
      ["Outdoor spigots", "North & east sides of house"],
      ["Smokes/CO status", "Replacement needed — smokes 3/28 (1 @ 3/27); CO's 2/30, mech room 3/28"],
    ],
  },
  {
    name: "16th Avenue",
    equipment: {
      waterSoftener: true,
      airExchanger: true,
      roofCoils: true,
      sumpPump: false,
      garbageDisposal: false,
      generator: false,
    },
    notes: {
      fridgeCoils: "Roof coils in garage by fuse box",
      furnaceFilter: "16x25x4",
      waterSoftener: "In the mechanical room — back left corner as you enter",
      shutoffs: "Main water: mech room, far right corner. Main gas: mech room, closest left corner. Outside water: one above water main in mech room; one in kitchen suspended ceiling under same panel as heat vent (access through small panel next to it, toward cabinet)",
      knives: "Top drawer to the left of the stove",
      medLock: "Magnetic key",
      dryerVents: "See house info",
    },
    info: [
      ["Mechanical room", "Located in the RS apartment"],
      ["MTX cabinet", "Back right corner of the garage"],
      ["Breaker box", "In garage"],
      ["Air exchanger", "Mech room, far right corner as you enter"],
      ["Furnace humidifier", "Yes"],
      ["Roof anchors", "This home has roof anchors"],
      ["Generator", "Removed — moved to another house"],
    ],
  },
  {
    name: "140th Lane West",
    equipment: {
      waterSoftener: true,
      airExchanger: false,
      roofCoils: false,
      garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): kitchen, on the wall above the garbage cans · RS (down): kitchen, on wall by office",
      furnaceFilter: "20x25x4",
      fridgeCoils: "Residents (up): front of the fridge · RS (down): back of the fridge",
      waterSoftener: "Yes",
      shutoffs: "Main water: mech room by utility sink. Main gas: next to / on furnace in basement. Outside water: both in mech room — one behind the furnace, one by laundry area",
      knives: "On the counter",
      medLock: "2 locks, 1 keypad. Stealth lock in kitchen (code in local codes file)",
      atticAccess: "Attic access: at the end of the hall by the rooms",
      dryerVents: "One by the back garage door; the other near the gas meter on right side",
    },
    info: [
      ["Paint", "Shelves in mechanical room — do NOT store paint in residential area of the house"],
      ["MTX cabinet", "Garage"],
      ["Electrical", "Both lower level: one in mechanical room, one in bedroom on west side of house"],
      ["Van key", "In the drawer by the garbage cans"],
      ["Roof coils", "None — ensure there is a roof rake"],
      ["Smokes/CO status", "Resident smokes rpl. 12/26; CO rpl. 12/28 & 8/31. RS smokes various dates, rpl. all by 10/28; CO's 3/30"],
    ],
  },
  {
    name: "92nd Crescent",
    equipment: {
      waterSoftener: true,
      airExchanger: true,
      sumpPump: false,
      garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "Residents (down): kitchen, far right cabinet; one in the van · RS (up): one under the sink, one in laundry room",
      furnaceFilter: "16x25x4",
      fridgeCoils: "See house info",
      waterSoftener: "In the laundry closet — use ONLY Morton System Saver II pellets",
      shutoffs: "Main gas and water: mechanical room. Outside water: both in mech room above the water heater",
      knives: "On the counter",
      medLock: "Digi Lock-C (code in local codes file)",
      atticAccess: "Attic access: in the live-in apt, in the laundry room",
      dryerVents: "RS (up): back of the house by patio · Residents (down): by front door",
    },
    info: [
      ["MTX cabinet", "Left wall of the garage"],
      ["Garbage disposal", "Upstairs only"],
      ["Fire stops", "Yes — both upstairs and downstairs"],
      ["Smokes/CO status", "Both levels — rpl. all by 7/2028 (several exp. dates currently); CO2's rpl. 3/2030"],
    ],
  },
  {
    name: "Amble",
    equipment: {
      waterSoftener: false,
      airExchanger: true,
      roofCoils: true,
      sumpPump: false,
      generator: false,
      garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "Under sinks and in laundry rooms up and down; and in the van",
      furnaceFilter: "90-day 20x25x4 — replace once every 90 days",
      waterSoftener: "None — this house does not have a water softener",
      shutoffs: "Main water: utility room. Main gas: utility room, next to the furnace. Exterior: back-of-house shutoff in cabinet under Resident-level kitchen sink; the faucet by the A/C is in the utility room ceiling at the back",
      knives: "Right of sink — second upper cabinet",
      atticAccess: "Attic access: ceiling of storage room next to utility room (garage light turns on attic light)",
      dryerVents: "Residents (down): east side of house · RS (up): back of house, middle vent next to porch (not under it); tall ladder needed",
    },
    info: [
      ["Paint", "Upstairs in the laundry room (most paint currently stored in the heated garage, 7/2022)"],
      ["MTX cabinet", "Garage, north wall by where the car parks"],
      ["Electrical box", "In the garage"],
      ["Gas meter", "East side of the house"],
      ["Van key", "On a hook by garage door"],
      ["Roof coils", "Switch on west wall of garage, just above the MTX cabinet"],
      ["Roof anchors", "Yes"],
      ["Shed", "Yes (no lock needed)"],
      ["Garbage disposal", "Upstairs yes / downstairs no"],
      ["Air exchanger", "Yes — clean pre-filters every 90 days; wash core filter each spring and fall"],
    ],
  },
  {
    name: "Barclay",
    equipment: {},
    notes: {
      furnaceFilter: "16x25x4 — Honeywell brand only",
      shutoffs: "Main water: furnace room. Main gas: furnace room. Exterior: utility room, both above/behind the water heater against the wall",
      medLock: "Digilock (code in local codes file)",
      dryerVents: "Residents (up): above patio door",
    },
    info: [
      ["Paint", "Downstairs in the office-area shelving"],
      ["Electrical box", "On garage wall"],
    ],
  },
  {
    name: "Bicentennial",
    equipment: {
      waterSoftener: true,
      airExchanger: false,
      roofCoils: true,
      sumpPump: true,
      generator: true,
      garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(3) Van · Residents (up): west kitchen wall · RS (down): under the sink in the basement apartment",
      waterSoftener: "Yes",
      shutoffs: "Main water: utility room, in front of the wash tub (kind of low). Main gas: attached to furnace. Exterior: front — utility room above sump pump; back — utility room back corner",
      knives: "Cabinet above microwave",
      atticAccess: "Attic access: in the hallway",
    },
    info: [
      ["Paint", "In the closet at the end of the hallway"],
      ["MTX cabinet", "Garage, along the east wall by the generator"],
      ["Electrical box", "Garage"],
      ["Utility room", "Basement apartment — through the door on the right in the kitchen"],
      ["Gas meter", "West front corner of house"],
      ["Van key", "Cabinet just left of the sun room door, next to the kitchen"],
      ["Grounding rod", "Right of the big garage door in the landscaping rock (as you look at the house); also 2ft left of the front outside faucet, 3ft out from house"],
      ["Emergency lanterns", "Garage, in a tote along the east wall by the MTX cabinet"],
      ["Roof coils", "Switch in garage by side door"],
      ["Roof anchors", "Yes"],
      ["Shed", "Yes (no lock needed)"],
      ["Sump pump", "Utility room — sealed for radon"],
      ["Air exchanger", "None"],
      ["Dryer vent", "Upstairs: just right of the front step"],
    ],
  },
  {
    name: "Boutwell",
    equipment: {
      waterSoftener: false,
      airExchanger: true,
      roofCoils: true,
      generator: true,
      garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(3) Van · Residents (up): under the sink · RS (down): under the sink",
      furnaceFilter: "90-day filter",
      waterSoftener: "None",
      shutoffs: "Main gas and water: furnace room. Exterior: both in utility room — one in the middle of the ceiling, one along the left wall behind the air-exchanger vent tubing (11/2021: one may have moved; both may be along the left wall). Right above a GFI outlet and power strip — cover/protect them when draining, the pipe sprays",
      knives: "On the counter",
      medLock: "Magnetic locks",
      atticAccess: "Attic access: back left bedroom",
      dryerVents: "Only one in use — back side of the roof",
    },
    info: [
      ["Paint", "MTX cabinet outside the utility room on the RS level"],
      ["MTX cabinet", "Garage"],
      ["Electrical box", "Garage"],
      ["Generator", "General GP 15000e"],
      ["Gas meter", "North side of the house by the air conditioner"],
      ["Van key", "Pantry right of the stove (pantry key in small drawer right of the stove); also med cabinet pantry right of the stove (cabinet key in small drawer right of the fridge)"],
      ["Roof coils", "Switch / GFI is under the breaker box in the garage"],
      ["Roof anchors", "None"],
      ["Shed", "None"],
      ["Sump pump", "Asleep/night room on the lower level"],
      ["Garbage disposal", "Upstairs none / downstairs yes"],
      ["Air exchanger", "Yes — under the steps in the office"],
    ],
  },
  {
    name: "Brooks",
    equipment: {
      waterSoftener: false,
      airExchanger: false,
      roofCoils: true,
      sumpPump: false,
      generator: false,
      garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(4) locations",
      furnaceFilter: "20x25x4",
      waterSoftener: "None",
      shutoffs: "Main water: mechanical room, straight ahead as you walk through the door. Main gas: mechanical room, behind the water heater and furnace. Exterior: front shutoff under the access panel in the RS bathroom ceiling; back shutoff in the RS laundry above the washer",
      knives: "Kitchen counter",
      atticAccess: "Attic access: see house info",
      dryerVents: "Only one in use — under the deck, not accessible; can only be cleaned from the inside",
    },
    info: [
      ["Paint", "Laundry room, north wall"],
      ["MTX cabinet", "Garage"],
      ["Gas meter", "Back of the house behind the garage"],
      ["Van key", "Inside the left door of the black cabinet just left of the office desk"],
      ["Grounding rod", "Just left of the garage door in the rocks, about a foot out from the garage"],
      ["Roof coils", "In laundry room"],
      ["Roof anchors", "Yes"],
      ["A/C unit", "Behind the garage"],
      ["Furnace humidifier", "Yes"],
      ["Garbage disposal", "Upstairs yes / downstairs no"],
    ],
  },
  {
    name: "Co. Rd. B2",
    equipment: {
      waterSoftener: false, airExchanger: false, roofCoils: true,
      generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(5) Van · Residents (up): hallway, under sink, garage · RS (down): under sink",
      furnaceFilter: "20x25x4 (90-day) — boiler downstairs for heat takes no filter; A/C unit in attic takes this filter",
      waterSoftener: "None",
      shutoffs: "Main water: RS apartment, off the living room by the fireplace — door to a closet, shutoff inside. Main gas: (see house). Exterior: front faucet in pump room off RS living room; back faucet not in service",
      knives: "In the Lazy Susan next to the stove",
      atticAccess: "Attic access: the garage",
      dryerVents: "Residents (up): on the deck · RS (down): by the fence for the trash, on the house",
    },
    info: [
      ["Paint", "MTX cabinet in hallway, opposite the two north bedrooms"],
      ["MTX cabinet", "Garage"],
      ["Fuse box", "Bedroom under upstairs living room; another behind the residents' washer/dryer in a locked closet adjacent to the upstairs kitchen"],
      ["Van key", "Office / sunroom"],
      ["Gas meter", "See house"],
      ["Roof coils", "Switch & GFI right next to the electrical box"],
      ["Roof anchors", "Yes"],
      ["Sump pump", "Closet by fireplace in live-in level"],
      ["Emergency lanterns", "Garage, by the MTX cabinet"],
      ["Garbage disposal", "Upstairs no / downstairs no"],
    ],
  },
  {
    name: "Crestridge",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: true, generator: false, garbageDisposal: true,
    },
    notes: {
      furnaceFilter: "Two furnaces: 20x25x4 (90-day) and 16x25x1 (90-day)",
      waterSoftener: "Yes",
      shutoffs: "Main water: utility room in the RS apartment, right of the furnace. Main gas: (see house). Exterior: utility room ceiling + one above the water softener — these 2 control front garage, back eastern corner, and apartment sliding door. The one front-right of the front door is disconnected/unusable",
      knives: "On the counter",
      medLock: "Front Stealth lock + cabinet lock (codes in local codes file)",
      atticAccess: "Attic access: large bathroom and the garage",
      dryerVents: "Residents (up): through the roof · RS (down): back under the deck (very long run; the RS dryer may auto-shut-off — coordinate with the live-in to keep it running while checking)",
    },
    info: [
      ["Paint", "Big storage room just past the living room"],
      ["MTX cabinet", "Garage, left of the big garage door"],
      ["Electrical box", "(2) First bedroom at the bottom of the stairs in the RS apartment; second in the utility room in the RS apartment"],
      ["Van key", "Front entry where the coats are hung"],
      ["Sump pump", "RS storage area — straight ahead as you walk in"],
      ["Emergency lanterns", "Garage, left of the big door, on top of the MTX cabinet"],
      ["Roof coils", "Switch in garage by door to house"],
      ["Roof anchors", "None"],
      ["Furnace humidifier", "Old, on the furnace, not operable"],
      ["Garbage disposal", "Upstairs yes / downstairs yes"],
    ],
  },
  {
    name: "Cummings",
    equipment: {
      waterSoftener: false, airExchanger: false, roofCoils: true,
      sumpPump: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(6) Under sink up and down · garage · by water heaters · van · bottom of the steps",
      furnaceFilter: "16x25x4 (90-day) — line up the airflow arrow on the filter with the furnace airflow direction",
      waterSoftener: "None",
      shutoffs: "Main water: utility room, near the floor along the east wall. Main gas: utility room, above the furnace. Exterior: garage-faucet shutoff on west side of mech room; right-side-of-house shutoff in RS small bedroom closet, under the ceiling access panel",
      knives: "Far right drawer",
      medLock: "Stealth lock + DidgiLock (codes in local codes file)",
      dryerVents: "Only one, front of the house at the bottom of the ramp (not hooked up). 2 roof vents serve the upstairs laundry-closet dryer — Comfort Solutions cleans these, not us",
    },
    info: [
      ["Paint", "Utility room downstairs (not RS apt), in a wall cabinet"],
      ["MTX cabinet", "Garage, by the big door"],
      ["Electrical box", "RS apartment small office room, to the left as you enter"],
      ["Van key", "Cabinet right of clock"],
      ["Shed", "Combination in local codes file"],
      ["Roof anchors", "Yes"],
    ],
  },
  {
    name: "Dale Court",
    equipment: {
      airExchanger: false, roofCoils: true, sumpPump: true,
      generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(2) Residents (up): under the kitchen sink · RS (down): under the kitchen sink",
      furnaceFilter: "Boiler for heat (no furnace filter). Upstairs ceiling filter in the hallway takes 14x25x1 — the RS changes this",
      shutoffs: "Main water: west bedroom in the RS apartment. Main gas: southwest bathroom in the RS apartment. Front water shutoff: entryway to the RS apartment, through the ceiling panel. Back water shutoff: northeast bedroom in the RS apartment",
      medLock: "DidgiLock (code in local codes file)",
      atticAccess: "Attic access: main hallway ceiling",
      dryerVents: "RS (down): south side of the house · Residents (up): on the roof",
    },
    info: [
      ["Paint", "Large closet in the main hallway"],
      ["Electrical / fuse boxes", "RS apartment, first room on your left after walking down the stairs"],
      ["Roof coils", "On brick wall in garage"],
      ["Roof anchors", "Yes"],
      ["Sump pump", "First room on your left down the stairs into the RS apartment — part of a sealed radon detection system"],
    ],
  },
  {
    name: "Dawn",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: true, garbageDisposal: false,
    },
    notes: {
      furnaceFilter: "Two furnaces, both take 20x25x4 (90-day)",
      waterSoftener: "Yes",
      shutoffs: "Main water: cubbie room in the office. Main gas: RS laundry room. Exterior: middle of ceiling above washer/utility-tub area; 2nd valve back corner of office near the ground by the Wel-Flo tank",
      medLock: "DidgiLock (code in local codes file)",
      atticAccess: "Attic access: garage",
      dryerVents: "Residents (up): east deck · RS (down): behind the house on the west side, under the deck where the brick blocks jut out, on top (not the disconnected one tucked way under the deck)",
    },
    info: [
      ["Paint", "Utility room area, across from the water heaters"],
      ["MTX cabinet", "Garage, along the west wall"],
      ["Electrical", "Back northwest bedroom downstairs — through the laundry room, the bedroom you walk into"],
      ["Van key", "Top left cabinet by radio"],
      ["Grounding rod", "Generator grounding rod: landscaping rock by the garage access door, right under the flag holder"],
      ["Gas meter", "Behind the house on the west side, between the steps and the house"],
      ["Emergency lanterns", "Tub in the garage on the MTX cabinet"],
      ["Roof coils", "Switch in garage by door to house"],
      ["Roof anchors", "Yes"],
      ["Sump pump", "RS laundry room"],
      ["Washing machines", "See house"],
    ],
  },
  {
    name: "Fallgold",
    equipment: {
      waterSoftener: true, roofCoils: false, sumpPump: true,
      garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "Residents (1st): on the cabinet in the kitchen · RS (2nd): laundry closet between washer and dryer · Basement (shared): bottom of the stairs · Van",
      furnaceFilter: "16x25x4 (90-day)",
      fridgeCoils: "Residents (1st): front side · RS (2nd): back of refrigerator",
      waterSoftener: "In the basement mechanical room",
      shutoffs: "Main water: next to water heater. Main gas: behind furnace. Exterior: one in the utility room ceiling right of the water softener; the other in the large downstairs room, southeast corner",
      knives: "In the right drawer of the island",
      atticAccess: "Attic access — RS (2nd): apartment hallway · Residents (1st): office area (for the garage) and in the hallway",
      dryerVents: "RS (2nd): back of the house above the sunroom · Residents (1st): back of the house by the patio",
    },
    info: [
      ["Paint", "In the basement by the mechanical room"],
      ["MTX cabinet", "Basement"],
      ["Mechanical room", "Basement, north end of house"],
      ["Electrical box", "Basement by the fridge and freezer"],
      ["Roof coils", "None — ensure there is a roof rake"],
      ["Sump pump", "Basement mechanical room"],
      ["Fire stops", "Both levels — replaced fall 2023"],
      ["Smokes status", "Replace smokes in 2021 (manufactured 2011)"],
      ["Garbage disposal", "Upstairs only"],
    ],
  },
  {
    name: "Fox Run Bay",
    equipment: {
      waterSoftener: false, airExchanger: true, roofCoils: false,
      sumpPump: true, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(3) Under sinks up and down · in the laundry room",
      furnaceFilter: "16x25x4 (90-day). Multiple auto zone dampers (don't switch them; Comfort Solutions services the damper motors)",
      waterSoftener: "None",
      shutoffs: "Main water: utility room downstairs, outside the RS apartment by the far wall. Main gas: utility room downstairs, outside the RS apartment next to the furnace. Exterior: one in the basement office access panel (ceiling); the other in the furnace room ceiling, just above the main water shut-off",
      knives: "In a block on the kitchen counter (unconfirmed)",
      atticAccess: "Attic access: hallway",
      dryerVents: "Roof / back of house",
    },
    info: [
      ["Paint", "Asleep-night room downstairs, closet by the water heaters"],
      ["MTX cabinet", "Garage"],
      ["Electrical box", "Garage, along the north wall by the MTX cabinet"],
      ["Grounding rod", "Garage corner (right front)"],
      ["Gas meter", "South side (front)"],
      ["Air exchanger", "Asleep-night room closet"],
      ["Roof anchors", "None"],
      ["Utility room", "(2) under the steps and the sleep room"],
      ["Sump pump", "Behind sleep-room curtain (right)"],
      ["Garbage disposal", "Upstairs yes / downstairs none"],
      ["Key switch (resident hall)", "Operates a door chime for the NW bedroom door — a switch in the utility room must be on for power, then turn the key to ON; speaker in front living room upper wall. Not in use"],
    ],
  },
  {
    name: "Fulham",
    equipment: {
      waterSoftener: false, airExchanger: false, garbageDisposal: false,
    },
    notes: {
      furnaceFilter: "20x25x1",
      shutoffs: "Main gas and water: mechanical room in the RS apartment — water shutoff on the far wall from the door; gas shutoff attached to the front of the furnace. Exterior: front — house storage closet in basement; back — RS bedroom closet (closet rod screwed to the access panel)",
      knives: "On top of the counter in a block",
      medLock: "Door handle (code in local codes file)",
      atticAccess: "Attic access: north end of the house, end of the hallway, in front of the westernmost bedroom",
    },
    info: [
      ["Paint", "Downstairs room next to garage — 5-gal bucket for most resident-level common-area walls (as of 9/9/21)"],
      ["Electrical box", "Bedroom at the end of the hall on the south side of the house (same hall as the laundry room)"],
      ["Van key", "See house"],
      ["Garage", "Downstairs — fake garage door in front; actual garage is lower level in the backyard"],
      ["Roof anchors", "Yes"],
      ["GFI (kitchen)", "The outlet near the phone trips a GFI button in the breaker box down the hall"],
      ["GFI (resident bathroom)", "When the large-bathroom GFI on the resident level trips, the fuse titled \"GFI\" also trips and must be reset for the outlet to work"],
    ],
  },
  {
    name: "Hillcrest",
    equipment: {
      airExchanger: false, roofCoils: true, sumpPump: true,
      generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): kitchen wall · RS (down): attached to wall · in house van",
      furnaceFilter: "20x25x4",
      waterSoftener: "See house",
      shutoffs: "Main water: closet behind the basement kitchen. Main gas: outside at the meter. Exterior: garage back-side faucet shutoff in the storage area off the RS kitchen (directly above the water main); one in ceiling to the right of the utility sink in RS apartment; back shutoff in RS laundry-room ceiling behind the big access panel, behind the black pipe",
      knives: "Block on kitchen counter",
      atticAccess: "Attic access: upstairs hallway, back and to the left, by the bathroom door",
    },
    info: [
      ["Paint", "Upstairs/exterior: bottom of staff bathroom closet + some in front closet. Downstairs: mostly back storage closet in RS apartment, some in closet off RS kitchen"],
      ["Electrical box", "Main in the garage; secondary on downstairs kitchen wall behind panel door"],
      ["Grounding rod", "Left of main garage door in the rocks, by downspout"],
      ["Roof coils", "In garage, by the door to the interior"],
      ["Roof anchors", "Yes"],
      ["Sump pump", "In three egress window wells (none in the basement itself); spare pump & hose by the MTX cabinet in garage"],
      ["Furnace humidifier", "Honeywell Aprilaire 560"],
    ],
  },
  {
    name: "Ilex",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: false, generator: false, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(4) Van · Residents (up): right of fridge · RS (down): just inside utility room and under the kitchen sink",
      furnaceFilter: "Two 30-day filters: 20x25 (front of unit) and 16x20 (backside)",
      waterSoftener: "Yes",
      shutoffs: "Main water: utility room, right of the wash tubs. Main gas: basement master bedroom (back right), closet ceiling. Exterior: 2 valves opposite the sink in the mech room — one against the west wall, one ~24\" from the west wall",
      knives: "Right of the microwave, a few in the drawer under the microwave to the right",
      atticAccess: "Attic access: back left bedroom closet",
      dryerVents: "Both outside the front door",
    },
    info: [
      ["Paint", "Closet cabinet to the right of the desk in the living-room area"],
      ["MTX cabinet", "Garage, along the west wall"],
      ["Electrical box", "RS bedroom"],
      ["Van key", "Hangs by the front door"],
      ["Garage key", "Hanging by the front door"],
      ["Grounding rod", "2ft left of the outside faucet, 3ft out from the house"],
      ["Gas meter", "Front north side of house"],
      ["Emergency lanterns", "Garage, by the MTX cabinet"],
      ["Roof coils", "By breaker box, in main bedroom in RS apt"],
      ["Roof anchors", "Yes"],
      ["Utility room", "Downstairs — through the basement apartment, door right of the kitchen fridge"],
      ["Garbage disposal", "Upstairs yes / downstairs no"],
      ["Washing machines", "Up: front-load / Down: top-load"],
      ["Smokes/CO status", "Resident: smokes battery 8/2019, 2×9/2019; HW 2×11/2019, 9/23; CO's 2×1/30. RS: change all smokes by 8/2029 (2 battery, 1 hardwire)"],
    ],
  },
  {
    name: "James",
    equipment: {
      waterSoftener: false, roofCoils: true, sumpPump: true,
      generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(4) Under both sinks, in the car, and in the garage by the door",
      furnaceFilter: "20x25x4 — Honeywell brand only",
      waterSoftener: "None",
      shutoffs: "Main water: utility room. Main gas: utility room. Exterior: both faucets are freezeless with no interior shutoffs",
      knives: "Locked in the med cabinet; key is the cabinet on the right above the desk",
      atticAccess: "Attic access: in the hallway",
      dryerVents: "Both on the north side of the house",
    },
    info: [
      ["Paint", "Utility room"],
      ["MTX cabinet", "Garage, along the south wall"],
      ["Electrical box", "RS dining area closet"],
      ["Van key", "See house"],
      ["Car key", "On a hook in the kitchen, by the door leading into the garage"],
      ["Grounding rod", "Generator grounding rod: rock landscaping to the north of the big garage door"],
      ["Roof coils", "By garage door by heat trace"],
      ["Roof anchors", "None"],
      ["Sump pump", "Utility room behind the furnace"],
      ["Shed", "No shed"],
    ],
  },
  {
    name: "Lancaster",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: false,
      sumpPump: true, garbageDisposal: false, frontLoadWashers: true,
    },
    notes: {
      fireExtinguishers: "Residents (up): garage · RS (down): mechanical room",
      furnaceFilter: "16x25x1 — use unpleated filter",
      waterSoftener: "Mech room, RS level — use ONLY Morton System Saver pellets",
      shutoffs: "Main water: bi-fold closet in the living room. Main gas: behind the water heaters in the mech room. Exterior: front — above the water meter in the closet off the RS living room; back — mech room, left of the furnace",
      knives: "In the med cabinet on the right",
      medLock: "DidgiLock (code in local codes file)",
      atticAccess: "Attic access: at the end of the hallway",
      dryerVents: "Residents (up): north end of the house, by the garbage cans · RS (down): east side of the house in the back yard",
    },
    info: [
      ["Paint", "Top shelf in the cabinet in the dining room / kitchen"],
      ["MTX cabinet", "Inside garage, right of ramp"],
      ["Electrical box", "Inside the garage, facing left"],
      ["Humidifier", "Mech room in RS apt"],
      ["Roof coils", "None"],
      ["Roof anchors", "Yes"],
      ["Sump pump", "Mech room in RS apt, left of dryer"],
      ["Front load washer", "Upstairs only"],
      ["Smokes/CO status", "Resident: smokes rpl. 12/28; CO2's rpl. 4/30 & 9/27"],
    ],
  },
  {
    name: "Larch",
    equipment: {
      waterSoftener: true, airExchanger: true, roofCoils: false,
      sumpPump: true, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(3) left of refrigerator (partial note from sheet)",
      furnaceFilter: "20x25x4 — Honeywell brand only",
      waterSoftener: "Yes",
      shutoffs: "Main water: mechanical room. Main gas: near furnace in mechanical room. Exterior: mechanical room — both have GREEN handles; one right above the main water valve, the other just to the right",
      medLock: "Magnetic locks",
      dryerVents: "Upstairs and downstairs right next to each other on the south side of the house, between the house and the wheelchair ramp",
    },
    info: [
      ["MTX cabinet", "See house"],
      ["Breaker box", "Asleep room in basement"],
      ["Air exchanger", "Two small pre-filters — white plastic pieces slide out and remain attached to the foam prefilter"],
      ["Van key", "Office by door leading downstairs"],
      ["Roof coils", "None — ensure there is a roof rake"],
      ["Roof anchors", "See house"],
      ["Sump pump", "Mechanical room next to the dryer"],
      ["Garbage disposal", "Upstairs"],
      ["Smokes/CO status", "Resident: smokes rpl. 5/28; CO2's 2×1/30. RS: rpl. 2×8/29, 1×6/31, 2×1/35; CO2 2×1/30"],
    ],
  },
  {
    name: "Lydia Ave",
    equipment: {
      airExchanger: false, roofCoils: true, sumpPump: true,
      generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(4) Inside garage by back door · van · Residents (up): kitchen behind the door · RS (down): under the sink",
      furnaceFilter: "20x25x4 (90-day)",
      waterSoftener: "See house",
      shutoffs: "Main water: back left bedroom (basement). Main gas: (see house). Exterior: one in the apartment ceiling by the fridge; one in the ceiling marked \"ws\", second tile in from the big window facing the backyard",
      knives: "Locked up above the microwave; key on the side of the microwave",
      atticAccess: "Attic access: garage, east wall",
      dryerVents: "Above the garage service door; no vent for the RS area",
    },
    info: [
      ["Paint", "Most at the top of the stairs closet; some in the downstairs office; some in the basement apartment kitchen closet"],
      ["Electrical box", "Downstairs in the closet next to the fireplace"],
      ["Van key", "Left cabinet door above the fridge"],
      ["Grounding rod", "To the left of the garage in the landscaping"],
      ["Roof coils", "In RS apt closet by fireplace, under breaker panel"],
      ["Roof anchors", "Yes"],
      ["Shed", "Yes (no lock needed)"],
      ["Sump pump", "(2) closet off the office area at the bottom of the RS-level stairs; second left of the fireplace in RS apartment, under the built-in hider (remove the loose top)"],
      ["Washing machine", "Top loader in kitchen"],
      ["Smokes/CO status", "Resi: smokes living rm exp 8/27, remainder exp 1/32 (change all for consistent dates — 1 hardwire, 3 battery); CO2 exp 10/25. RS: smokes 1/34 battery & hardwired; CO2 exp 2/30"],
    ],
  },
  {
    name: "Lydia West",
    equipment: {
      waterSoftener: false, airExchanger: false, roofCoils: true,
      sumpPump: true, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(4) Van · Residents (up): kitchen, laundry · RS (down): under kitchen sink",
      furnaceFilter: "Honeywell 16x25x4",
      waterSoftener: "None",
      shutoffs: "Main water: storage room in apt, next to sprinkler gauge. Main gas: furnace room ceiling. Exterior: front faucet shutoff in the front storage room; back shutoff in the RS bedroom under the ceiling tile next to the rear exterior wall — third tile from the left facing the rear wall",
      knives: "Closet by the front door; key is the blue one in the cubbies between the kitchen and living room",
      medLock: "Stealth lock (code in local codes file)",
      dryerVents: "Just one hooked up — west side of the house",
    },
    info: [
      ["Paint", "Lower cabinet in the living room"],
      ["MTX cabinet", "Garage"],
      ["Electrical panel", "One behind the panel next to the stove in the basement apartment; the other in the back bedroom on the left"],
      ["Van key", "Cubbies between the kitchen and living room"],
      ["Grounding rod", "Front landscaping by the garage"],
      ["Gas meter", "West side of the house near the front"],
      ["Roof coils", "Switch next to the electrical panel in the bedroom of the apartment"],
      ["Roof anchors", "Yes"],
      ["Shed", "Yes — yellow key in the cubbies between the kitchen and living room"],
      ["Sump pump", "West side, bottom of the steps (outside) at the basement apartment entry door"],
    ],
  },
  {
    name: "Magnolia",
    equipment: {
      waterSoftener: true, airExchanger: true, roofCoils: false,
      garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): laundry room by the washing machine · RS (down): one in mechanical room, one under the kitchen sink",
      furnaceFilter: "16x25x4",
      waterSoftener: "In mechanical room",
      shutoffs: "Main water: mech room by water heater. Main gas: attached / next to furnace on the right-hand side. Exterior: right side — above ceiling panel in mech room above the water softener; left side — left of the HRV",
      knives: "On the counter",
      medLock: "Magnetic",
      atticAccess: "Attic access: hallway back by the bedrooms",
      dryerVents: "Residents (up): under deck · RS (down): (see house)",
    },
    info: [
      ["Paint", "Upstairs: closet next to the laundry closet · Downstairs: closet in room off kitchen"],
      ["Breaker box", "In garage, wall by double garage door"],
      ["Air exchanger", "In mechanical room"],
      ["Roof coils", "None — ensure there is a roof rake"],
      ["Garage door", "No chain — cable driven"],
      ["Smokes/CO status", "Both levels — smokes rpl. 4/2028 & 10/2028; CO's rpl. 2/2030"],
    ],
  },
  {
    name: "McAfee",
    equipment: {
      waterSoftener: false, airExchanger: true, sumpPump: false,
      garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(3) Under both sinks up and down, and in the staff closet across from the main bathroom. No house van here",
      furnaceFilter: "14x25x1 (30-day) — change monthly",
      waterSoftener: "None",
      shutoffs: "Main gas and water: both in the furnace room. Exterior: resident level — in cabinet on the right of the range, both shutoffs",
      knives: "In the staff closet across from the main bathroom",
      medLock: "DidgiLock (code in local codes file)",
      atticAccess: "Attic access: RS apartment",
      dryerVents: "Residents (down): south side · RS (up): back of house",
    },
    info: [
      ["Paint", "Bottom of the small closet just right of the main bathroom (locked door)"],
      ["MTX cabinet", "Garage"],
      ["Electrical box", "Garage, left of the fridge"],
      ["Gas meter", "North side of house"],
      ["A/C unit", "South side"],
      ["Air exchanger", "Laundry room on the resident level"],
      ["Shed key", "Hanging by MTX cabinet, or RS has one"],
      ["Roof anchors", "See house (?)"],
      ["Garbage disposal", "Upstairs yes / downstairs none"],
    ],
  },
  {
    name: "McMenemy",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: true, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "Residents (up): under kitchen sink, cleaning closet (by front door), laundry · RS (down): office, furnace room · Van",
      furnaceFilter: "Two 90-day filters: 16x25x4 and 16x25x1 (RS apartment furnace takes a pleated 90-day 1\" per Comfort Solutions)",
      waterSoftener: "Utility room",
      shutoffs: "Main water: downstairs in the RS apartment closet off the kitchen. Main gas: above the furnace in the utility room (at the bottom of the stairs, look up and to the right); also one in the furnace room in the RS apartment. Exterior: office downstairs above the water heater; far-left closet in the basement apartment dining area, just above the cement doorway going into the main water shutoff",
      knives: "In the locked pantry cabinet just right of the doorway to the hallway; key hangs on the right side of the cabinet",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: hallway by the laundry doors (ignore the attic access in the first closet by the kitchen — it doesn't open)",
      dryerVents: "One in front of the house, left of the left front door. Basement dryer is not hooked up",
    },
    info: [
      ["Paint", "Front closet of the green living room"],
      ["MTX cabinet", "Garage, along the west wall"],
      ["Electrical box", "RS apartment kitchen, by the fridge"],
      ["Car key", "Hallway closet closest to the kitchen, on the inside of the door in an envelope"],
      ["Grounding rod", "Left of garage door"],
      ["Gas meter", "Front of the house, just left of the left front door"],
      ["Roof coils", "Switch / GFI in the garage next to the peg board"],
      ["Roof anchors", "Yes"],
      ["Sump pump", "Left closet in the kitchen"],
      ["Water alarms", "Up: under kitchen sink, laundry room, 2 in tan bathroom, 3 in green bathroom. Down: 2 in utility room, 1 by sump pump in apt, 1 under kitchen sink in apt, 1 under bathroom sink"],
      ["Garbage disposal", "Upstairs yes / downstairs yes"],
    ],
  },
  {
    name: "Alta Vista",
    equipment: {
      waterSoftener: false, airExchanger: false, sumpPump: true,
      generator: true, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(4) Cabinet next to meds in dining room · hallway cabinet to resident rooms · laundry room · mudroom (next to garage)",
      furnaceFilter: "Honeywell 16x25x4 — three: one in mechanical room, one in garage, one in mudroom off of garage (downstairs apartment)",
      shutoffs: "Main water: mechanical room off the basement apartment. Main water & gas: west bedroom of the basement apt. Main gas: outside the patio access for the basement apartment. Outside water: front — lower-level mudroom just off the garage; back — north-side utility room, in the ceiling straight up about 3 ft past the door entrance (it seems to turn on a spigot in the yard too — go back in the yard and check)",
      knives: "Lazy susan in kitchen",
      medLock: "Keypad med lock + locked kitchen drawer (codes in local codes file). The IEI isn't in use anymore",
      atticAccess: "Attic access: 2nd bedroom",
      dryerVents: "One — northwest corner of house",
    },
    info: [
      ["Paint", "Garage"],
      ["MTX cabinet", "Garage"],
      ["Van key", "In the van backpack just inside the office door on the right, in the side pocket"],
      ["Shed key", "On the cabinet door on the west wall across from the kitchen sink; also a key hanging in the MTX cabinet"],
      ["Roof anchors", "Yes"],
      ["Sump pumps", "Two: patio area outside on the south side; main mechanical room, northwest corner"],
      ["Generator", "Yes — stationed in the garage"],
      ["Gas meter", "South side of the house"],
      ["Electric/fuse boxes", "1st in maintenance room, lower level below the living room; 2nd in the garage"],
      ["Furnace humidifier", "Yes"],
      ["A/C units", "Two — the big one at the back of the house, a smaller one in front"],
      ["Garbage disposal", "Upstairs no / downstairs no"],
    ],
  },
  {
    name: "Jennifer Court",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: true, generator: false, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(4) Residents (up): normal and grease under the sink · RS (down): under the sink · van",
      furnaceFilter: "20x25x4",
      waterSoftener: "Downstairs office",
      shutoffs: "Main water: office/utility room. Main gas: office/utility room. Outside water: front and back shutoffs next to each other on the ceiling above the wash tub in the downstairs furnace room",
      knives: "Block by stove",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: two — one by upstairs bathroom near front door, one in garage",
      dryerVents: "(2) Between addition and house (south) · near front door railing",
    },
    info: [
      ["Paint", "Office"],
      ["MTX cabinet", "Garage"],
      ["Van key", "Van bag in the closet by the front door; spare stored in office — small drawer on upper left of desk"],
      ["Utility room", "Downstairs office outside of the live-in apt — no apt entrance required"],
      ["Sump pump", "Bottom of stairs"],
      ["Roof coils", "Breaker box, fuse 11 (possibly #21 — 10/2023)"],
      ["Electrical boxes", "Two: one in garage, one in live-in apt by stairs"],
      ["Furnace humidifier", "None"],
      ["Garbage disposal", "Upstairs yes / downstairs not operational"],
      ["Hose reel", "10/2023: the back-yard hose reel broke — need a new one. RS asked that the hose not be stored in the garage without the reel, so for this winter it is under the deck. The black hose connects the spigot to the other one next to the A/C compressor (one hose for each side)"],
    ],
  },
  {
    name: "Oakwood",
    equipment: {
      waterSoftener: true, airExchanger: false, sumpPump: false,
      generator: false, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(4) Van · Residents (up): under sink, laundry · RS (down): (not filled in on the sheet)",
      furnaceFilter: "16x25x1",
      waterSoftener: "Utility room",
      shutoffs: "Main water: storage room. Main gas: furnace room — look up. Outside water: 1) storage room near wall; 2) behind panel in washer room (next to utility room)",
      atticAccess: "Attic access: two — 1st bedroom on the left, and the garage",
      dryerVents: "Just one hooked up — at the back of the house by the ramp",
    },
    info: [
      ["Paint", "Office"],
      ["MTX cabinet", "Garage"],
      ["Van key", "On hook by the front door"],
      ["Shed", "Yes (no lock needed)"],
      ["Roof anchors", "Yes"],
      ["Grounding rod", "North east corner"],
      ["Gas meter", "South west corner"],
      ["Electrical", "Back bedroom"],
      ["Furnace humidifier", "Yes"],
      ["Garbage disposal", "Upstairs yes / downstairs no"],
    ],
  },
  {
    name: "Regent",
    equipment: {
      waterSoftener: true, airExchanger: true, sumpPump: true,
    },
    notes: {
      fireExtinguishers: "Residents (up): closet in dining room · RS (down): in the cabinet under the island",
      furnaceFilter: "20x25x4 — Honeywell brand only",
      waterSoftener: "In the mechanical room",
      shutoffs: "Main water: mech room by the water heaters. Main gas: mech room by the furnace. Outside water: left side of house — under the RS kitchen sink; right side — mech room above the laundry tub",
      knives: "Little drawer to the right of the dishwasher",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: at the end of the hallway",
      dryerVents: "Residents (up): on the south wall, under the ramp to the deck · RS (down): north wall",
    },
    info: [
      ["Paint", "Some upstairs in the closet next to the laundry; most of it down in the mechanical room"],
      ["MTX cabinet", "Garage, in the northwest corner"],
      ["Sump pump", "Closet under the stairs, room behind kitchen"],
      ["Air exchanger", "In the mechanical room above the washer and dryer"],
      ["Garage keypad", "Replaced 06/24/2026 (code in local codes file)"],
      ["Smokes/CO status", "Resident — smokes: HW rpl. 9/2027, battery rpl. 6/2031; CO rpl. 2/2030. RS level — smokes 4x rpl. 8/27; CO 2/30 & 4/26"],
    ],
  },
  {
    name: "Riverdale",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: true, generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(6) Van · Residents (up): kitchen (hanging on the wall), laundry (on the wall to the left) · RS (down): under kitchen sink, closet in the second living room (just right of laundry room) · 1 in the garage",
      furnaceFilter: "90-day 20x25x4",
      waterSoftener: "Yes",
      shutoffs: "Main water: west wall of the RS living room, under a panel. Main gas: at the meter. Outside water: RS level — one above the softener, one in the storage room above the laundry tub",
      knives: "On the counter",
      atticAccess: "Attic access: hallway",
      dryerVents: "Both on the south side. Residents (up): right of the faucet in the corner · RS (down): left of the faucet",
    },
    info: [
      ["Paint", "Two locations: resident-level paint in the hall closet at the bottom; RS-level paint down in the RS storage room by the work bench"],
      ["MTX cabinet", "In the garage by the door going into the house"],
      ["Van key", "In the office, in the house mail bin"],
      ["Shed", "Yes (no lock needed)"],
      ["Roof coils", "Switch near one of the electrical boxes: east wall of the RS storage room"],
      ["Roof anchors", "Yes"],
      ["Sump pumps", "Two: storage room off the hall in the RS apartment (across from the laundry room, back in the corner); window well on the south side of the house"],
      ["Generator", "Riverdale no longer has a generator"],
      ["Grounding rod", "4.5 feet right (south) of the garage door and 1 foot out from the front of the house"],
      ["Electrical boxes", "Two: RS storage room, east wall; utility room in the RS apartment"],
      ["Furnace humidifier", "None"],
      ["Smokes/CO status", "Resident — smokes 7/29, 8/29, 9/31, many other dates; CO 6/28, 3/30"],
    ],
  },
  {
    name: "Robin Ave",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: false, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "Residents (up): kitchen and hallway · In the van · RS (down): under sink and furnace room",
      furnaceFilter: "16x25x4 — Honeywell",
      waterSoftener: "Takes the softener pellets — needs to be kept full of salt to the water line",
      shutoffs: "Main water: RS apartment utility room, on the far west wall. Outside water: one in mech room, left of washer; one in the bedroom on the left, outside of the closet, in the ceiling next to the wall",
      knives: "Top left drawer, left of the dishwasher. The key for the drawer is in the med cabinet (med combo in local codes file)",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: above washer and dryer",
      dryerVents: "Residents (up): vented through the roof · RS (down): vent comes out on the front ramp",
    },
    info: [
      ["Paint", "In the right front hallway closet across from the med closet"],
      ["MTX cabinet", "None — a few maintenance items in the office closet, a cabinet in the med closet, and with the paint storage"],
      ["Van key", "Hanging on the wall in the white box with drawers in the living room by the front door"],
      ["Roof coils", "Switch in apt utility room, left of dryer"],
      ["Roof anchors", "Yes"],
      ["Master key", "None needed — ICF houses do not need the resident bedroom doors to have the kwik-set doorknobs"],
      ["Gas meter", "South side of the house at the front corner"],
      ["Electrical box", "RS apartment southwest bedroom (breakers are horribly labeled)"],
      ["Furnace humidifier", "None"],
      ["Petty cash box", "In med cabinet"],
      ["Garbage disposal", "Upstairs no / downstairs yes"],
    ],
  },
  {
    name: "Robin Court",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: true, generator: true,
    },
    notes: {
      furnaceFilter: "Normal 16x25x4",
      waterSoftener: "Downstairs hallway closet next to the furnace/heater closet",
      shutoffs: "Main water: back bedroom closet. Outside faucet shutoffs: one above the laundry tub on the RS level; one in the master bedroom closet, in the ceiling, left side",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: end of hallway, in front of small bathroom",
    },
    info: [
      ["Van key", "Closet by front door, hanging on the inside wall"],
      ["Roof coils", "Switch next to the electric box, in the first bedroom around the corner"],
      ["Roof anchors", "Yes"],
      ["Electric box", "First bedroom around the corner"],
      ["Sump pumps", "Four: small closet in the small bedroom in the RS apt; bathroom closet in the RS bathroom; two outside — one under the steps from the RS patio, one near the mound on the southwest corner of the property"],
      ["Generator", "Yes"],
      ["Furnace humidifier", "None"],
      ["Air exchanger", "None"],
    ],
  },
  {
    name: "Sherwood Place",
    equipment: {
      waterSoftener: true, airExchanger: true, sumpPump: false,
      generator: false,
    },
    notes: {
      fireExtinguishers: "Residents (down): left of the sink · RS (up): under the sink · one mounted on the garage wall · one in the house van",
      furnaceFilter: "20x25x4 — should be changed every 90 days by the live-in or RS",
      waterSoftener: "In furnace room",
      shutoffs: "Main water: furnace room, left side wall, down low. Main gas: furnace room, right side, attached to furnace duct work. Outside faucet shutoffs: both on the back wall of the furnace room, above the water softener",
      knives: "Knife block on the kitchen counter; also check the drawer to the left of the oven",
      medLock: "Same style as the apt door locks (code in local codes file)",
      atticAccess: "Attic access — RS (up): laundry room; will need the 6 ft ladder",
      dryerVents: "On the back of the house, up high — will need a stepladder, or access them from the deck stairs",
    },
    info: [
      ["Paint", "Front closet — the closet to the left of the door into the garage"],
      ["Furnace room", "Door to the right of the door into the garage (immediately to your left walking into the house)"],
      ["Electrical box", "In the garage above the MTX cabinet"],
      ["GFI", "Both Resident-level bathrooms are on the same GFI, linked to the Master Bathroom on the RS level where the reset switch is"],
      ["Roof anchors", "None"],
      ["Air exchanger", "Mounted on back wall of furnace room"],
      ["Smokes/CO status", "Resident level — 3x CO rpl. 4/27, 6x smokes rpl. 12/27 (to sync dates), all wired. RS area — 1x CO rpl. 2/30, 4x smokes rpl. 12/27 (same as upstairs)"],
    ],
  },
  {
    name: "Skycroft",
    equipment: {
      waterSoftener: true, airExchanger: false, sumpPump: false,
      generator: false, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(4) Garage, laundry, van, and under sink",
      furnaceFilter: "90-day 20x25x4 — maintenance changes it on the house visit",
      waterSoftener: "Yes",
      shutoffs: "Main water: in the storeroom down the hallway past the laundry room and furnace room. Outside water: rear spigot — master bedroom closet ceiling; front spigot — storage area at the front of the house, in the ceiling next to the main shutoff",
      knives: "On the counter",
      medLock: "Med cabinet keypad (code in local codes file)",
      atticAccess: "Attic access: in the med closet in the hallway by the washer/dryer — 2 shelves to stand on plus a small ladder to get up",
      dryerVents: "Both on the north side of the house",
    },
    info: [
      ["Paint", "At the end of the long storage closet downstairs"],
      ["MTX cabinet", "Garage"],
      ["Van key", "Top cabinets to the right of the sink"],
      ["Shed", "Yes (no lock needed)"],
      ["Roof anchors", "Yes"],
      ["House code", "None"],
      ["Electrical box", "Office downstairs in the RS's apartment"],
      ["Garbage disposal", "Upstairs no / downstairs yes"],
    ],
  },
  {
    name: "Sunbury",
    equipment: {
      sumpPump: true, airExchanger: true,
    },
    notes: {
      furnaceFilter: "16x25x4 90-day — needs to be changed every 3 months",
      shutoffs: "Main water: RS apartment utility room (in the bathroom). Main gas: RS apartment utility room, in the bathroom next to the furnace. Outside water: front faucet shutoff under the kitchen sink on the resident level; back faucet shutoff in the RS apartment utility room, on the ceiling above the water softener",
    },
    info: [
      ["Sump pump", "In the bedroom off the kitchen in the RS apartment"],
      ["Electrical box", "On the far wall of the garage"],
      ["Air exchanger", "In the utility room in the RS bathroom"],
    ],
  },
  {
    name: "Tiller Lane",
    equipment: {
      waterSoftener: false,
    },
    notes: {
      fireExtinguishers: "Garage, under kitchen sink, van, RS apartment (down), and laundry room",
      furnaceFilter: "20x25x4",
      waterSoftener: "N/A",
      shutoffs: "Main water: southwest corner of the basement apartment kitchen, behind the lazy susan. Main gas: north end of the basement apartment kitchen above the washer/dryer (a washer/dryer may not be hooked up — you'll see the duct and pipe ready for one). Outside water: front faucet shutoff in the storage room off the mech room; back faucet shutoff in the RS apartment small bedroom under the ceiling access panel",
      medLock: "Medicine closet keypad (code in local codes file)",
      atticAccess: "Attic access: western hallway ceiling",
      dryerVents: "On the front of the house at the end of the ramp",
    },
    info: [
      ["Paint", "Down in the storage/laundry room in a closet"],
      ["Electrical panel", "In garage"],
    ],
  },
  {
    name: "Toledo",
    equipment: {
      waterSoftener: false, roofCoils: true,
    },
    notes: {
      fireExtinguishers: "(3) Residents (up): laundry closet · RS (down): under kitchen sink · One in the van",
      furnaceFilter: "Two furnaces — both 20x25 (a 1-inch and a 4-inch filter)",
      fridgeCoils: "Residents (up): front of fridge · RS (down): back of fridge",
      waterSoftener: "None",
      shutoffs: "Main water: mechanical room. Main gas: at the meter. Outside water: front — RS laundry room behind the furnace, up in the ceiling; back — mech room above the water heater",
      knives: "Above the pantry — most are serrated",
      medLock: "Stealth lock — 1 keypad, 3 locks (code in local codes file)",
      atticAccess: "Attic access: in the closet of the back bedroom on the right",
      dryerVents: "Residents (up): on the back of the house · RS (down): on the front of the house",
    },
    info: [
      ["Paint", "In the closet at the bottom of the stairs by the RS apartment"],
      ["Roof coils", "Switch in garage, by the trash"],
      ["Furnace humidifier", "In mechanical room on the right"],
      ["Grounding rod", "On the southeast corner of the garage"],
      ["Breaker box", "In left bedroom in live-in apartment"],
      ["Smokes/CO status", "Resident — smokes 1/35 hallway, 1/31, 2@3/30, 2@2/32 battery; CO 2/30. RS — smokes 4/29, 2x 1/31, 2/26, 10/31 battery; CO 2/30 & 4/30"],
    ],
  },
  {
    name: "Trenton Lane",
    equipment: {
      sumpPump: true, roofCoils: false, generator: false,
    },
    notes: {
      furnaceFilter: "Two furnaces: 16x25x1 fiberglass + 20x25x4 Honeywell brand only, change monthly (one sheet row lists '6x25x4' — verify size on site)",
      shutoffs: "Main water: by the water heater. Main gas: in front of the furnace. Outside water: both are in the next room to the right of the water heaters, connected to the water main entry, about 5 feet off the ground",
      dryerVents: "Resident dryer vents through the roof",
    },
    info: [
      ["Thermostats", "One on each level"],
      ["Sump pump", "Laundry closet downstairs"],
      ["Furnace", "In the RS apartment"],
      ["Roof coils", "None — ensure there is roof rakes"],
      ["Electrical", "In the garage"],
      ["Emergency light", "In mechanical room"],
      ["Driveway", "Asphalt"],
      ["A/C unit", "In back of house"],
      ["CO detectors", "Kidde — two in the hall on Resident level, one in hall on RS level"],
    ],
  },
  {
    name: "Valders",
    equipment: {
      waterSoftener: false, airExchanger: false, roofCoils: true,
      garbageDisposal: false, frontLoadWashers: true,
    },
    notes: {
      fireExtinguishers: "Residents (up): above kitchen sink on cabinet · Van: on passenger seat · RS (down): under kitchen sink",
      furnaceFilter: "90-day 20x25x4",
      waterSoftener: "None",
      shutoffs: "Main water: in the utility room on the right half of it. Main gas: on the furnace. Outside water: 2 shutoffs in the mech room by the storage shelves — one is above the main water shutoff",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: in the garage",
      dryerVents: "Residents (up): right outside the garage door · RS (down): right outside the garage door",
    },
    info: [
      ["Roof coils", "Switch located by breaker box in mech room"],
      ["Breaker boxes", "One in the furnace room downstairs; the other in the RS apartment at the end of the hall, in the room on the right"],
      ["Furnace humidifier", "None"],
      ["Front-load washer", "Downstairs only"],
      ["Smokes/CO status", "CO's all levels — replace 2/2030. Smokes — Resident level: 1 rpl. 2027 hallway, remaining 4/2034; RS level: rpl. all 1/28"],
    ],
  },
  {
    name: "Oregon Brooklyn Park (OBP)",
    equipment: {
      waterSoftener: true, airExchanger: true, garbageDisposal: true,
      frontLoadWashers: true,
    },
    notes: {
      fireExtinguishers: "Residents (up): in the kitchen by the cabinet; also one in the garage · RS (down): under the kitchen sink",
      furnaceFilter: "20x25x4 — Honeywell brand only",
      waterSoftener: "Basement mech. room",
      shutoffs: "Main water: mechanical room, between the furnace and water heater. Main gas: mechanical room, on the wall by the furnace. Outside water: both shutoffs left of the furnace",
      knives: "In the cabinet to the right of the stove",
      medLock: "Stealth locks (code in local codes file)",
      atticAccess: "Attic access: at the end of the hallway",
      dryerVents: "Residents (up): on the roof · RS (down): on the east end of the house",
    },
    info: [
      ["Paint", "Basement — back room closet"],
      ["MTX cabinet", "Garage"],
      ["Mechanical room", "RS apt, first door on the right"],
      ["Grounding rod", "On the front of the home, about 2 feet to the left of the step"],
      ["Power panel", "In the storage room off the kitchen, on the far wall"],
      ["Roof anchors", "Yes"],
      ["Air exchanger", "In the mech. room"],
      ["A/C unit", "On the east side of the house"],
      ["Front-load washer", "Resident level"],
      ["Fire stops", "Replace 2029"],
      ["Garbage disposal", "Downstairs only"],
      ["Smokes/CO status", "Smokes — 4 up, 4 down (various dates), replace all by 9/27. CO's — 2 up, rpl. 3/30, 2/31; RS level rpl. 11/30"],
    ],
  },
  {
    name: "Redwood",
    equipment: {
      waterSoftener: true, airExchanger: false, roofCoils: true,
      sumpPump: false, garbageDisposal: true,
    },
    notes: {
      fireExtinguishers: "(6) Van, kitchen, front closet, dryer closet upstairs, sleep room, under sink downstairs",
      furnaceFilter: "14x25x1 30-day — change monthly",
      waterSoftener: "Yes",
      shutoffs: "Main water: RS apartment bedroom next to the utility room. Outside faucet shutoffs: by the main shutoff (inside closet by the patio door); also inside the wood cabinet in the spare room — the shutoff is up high inside the wall cabinet. RS level: one in the pantry closet in the addition, one in the small bedroom closet with face frame, in the ceiling",
      knives: "The lazy susan",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: one right above the garage entrance door (accessible), and one in the laundry closet that is super hard to get to — so use the garage access",
      dryerVents: "RS (down): comes out at the front of the house under the kitchen window · Residents (up): on the north side of the house, up high",
    },
    info: [
      ["Paint", "In a metal cabinet down in the utility room"],
      ["MTX cabinet", "In the garage along the back wall"],
      ["Van key", "Kitchen cabinet closest to dining table"],
      ["Shed", "Yes (no lock needed)"],
      ["Roof coils", "The switch is by the garage door"],
      ["Roof anchors", "Yes"],
      ["Grounding rod", "In the landscaping to the south of the big garage door, between the sidewalk and garage"],
      ["Electrical boxes", "RS apartment first living room along the west wall; another in the closet off the addition in the RS apartment"],
      ["Furnace humidifier", "None"],
      ["A/C units", "(5) 3 outside on the north side — 1 big one and 2 smaller ones down the hill; 2 inside — one in the living room downstairs, one in the sunroom upstairs"],
      ["Garbage disposal", "Upstairs yes / downstairs no"],
    ],
  },
  {
    name: "Oregon Golden Valley (OGV)",
    equipment: {
      waterSoftener: false, airExchanger: false, generator: true,
      garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "Residents (up): laundry closet and in kitchen next to fridge · RS (down): under kitchen sink, van, garage",
      furnaceFilter: "20x25x4",
      fridgeCoils: "Residents (up): front/back · RS (down): front/back",
      waterSoftener: "None",
      shutoffs: "Main water: in the laundry room. Main gas: at meter. Outside water: RS level — the front faucet valve is in the back bedroom behind the ceiling access panel that is close to the closet; the back faucet valve is in the laundry room above the door",
      knives: "Med cabinet",
      medLock: "Stealth lock (code in local codes file)",
      atticAccess: "Attic access: little storage closet in office area",
      dryerVents: "Residents (up): roof · RS (down): on north side of the house",
    },
    info: [
      ["MTX cabinet", "Garage"],
      ["Van key", "Drawer right by the entryway to the living room"],
      ["Generator", "Yes — in the garage"],
      ["Fire stops", "Magnet type — rpl'd 8/23"],
      ["Smokes/CO status", "Resident — rpl. smokes 2/27 & 6/28; rpl. CO 3/30. RS — various dates, replace all 2/28; CO rpl. 8/30"],
    ],
  },
  {
    name: "Riverton",
    equipment: {
      waterSoftener: true, airExchanger: false, sumpPump: false,
      generator: false, garbageDisposal: false,
    },
    notes: {
      fireExtinguishers: "(3) One in the van · Residents (up): in the cabinet right of the fridge · RS (down): in the cabinet just right of the dishwasher",
      furnaceFilter: "20x25x4 — Honeywell brand only",
      waterSoftener: "Yes",
      shutoffs: "Main water: RS apartment, in the closet off the kitchen, right next to the front outside water shutoff. Main gas: RS apartment utility room, in front of the furnace. Outside water: backyard shutoff behind the cover box in the ceiling just above the entrance to the utility room; front yard in the pantry left of the dishwasher — both in the basement apt",
      knives: "In the far right pantry to the right of the fridge (this is also the med cabinet)",
      atticAccess: "Attic access: in the hallway upstairs",
      dryerVents: "Residents (up): super short run straight out on the west side of the house · RS (down): (not filled in on the sheet)",
    },
    info: [
      ["Paint", "Back closet in RS level office"],
      ["MTX cabinet", "In the garage next to the door that goes into the house"],
      ["Van key", "Coat closet by the front door (box code in local codes file)"],
      ["Spare key", "See local codes file"],
      ["Shed", "None"],
      ["Roof anchors", "None"],
      ["Grounding rod", "Right corner of the house, about a foot out from the house going west and about 6 inches set in"],
      ["Electrical box", "In the RS apartment in the back bedroom at the end of the hall"],
      ["Furnace humidifier", "None"],
      ["Garbage disposal", "Upstairs none / downstairs none"],
    ],
  },
  {
    name: "Emmert",
    equipment: {
      waterSoftener: true, sumpPump: true, generator: true,
      garbageDisposal: false,
    },
    notes: {
      furnaceFilter: "16x25x4 — two furnaces",
      waterSoftener: "In the utility area",
      shutoffs: "Main water: mechanical room, behind the water softener. Main gas: at the meter on the north side of the house. Outside water: both in the basement utility-room ceiling — front in front of the water heater; back in front of the water softener. Two PVC valves that need adjusting in spring & winter are in the corner next to the water heaters",
      medLock: "Stealth lock — 5 locking cabinets in the kitchen (code in local codes file)",
      dryerVents: "Three on the north side of the house. The one on the right takes 3 full packs of rods; one of the two on the left needs a ladder to reach",
    },
    info: [
      ["Sump pumps", "Three — two in the mechanical room, one in the closet under the stairs"],
      ["MTX cabinet", "Closet under the stairs (no cabinet)"],
      ["Grounding rod", "In the rock bed to the right of the garage (facing the garage doors), among the bushes — one is growing over the rod, so it's kind of hidden"],
      ["Generator", "This house has two generators"],
      ["Electrical boxes", "Two panels at the north end of the mechanical room in the basement"],
      ["Door keypads", "Installed & serviced by Electrical Watchmen — contact: Ben 651-310-1268"],
    ],
  },
];
