-- ----------------------------------------------------------------------------
-- 0004_more_houses.sql — additional houses beyond the two seeded in 0001.
--
-- Mirrors the equipment/notes/info JSONB shapes used in house-data.js.
-- Door/entry codes are NEVER stored here (public repo) — they live only in
-- house-codes.local.js on-device.
--
-- Apply by hand in the Supabase dashboard SQL Editor. Safe to re-run:
-- `on conflict (name) do nothing` skips houses already present.
-- ----------------------------------------------------------------------------
insert into public.houses (name, equipment, notes, info) values
('140th Lane East',
 '{"waterSoftener": true, "airExchanger": true, "garbageDisposal": false, "frontLoadWashers": false}'::jsonb,
 '{"fireExtinguishers": "Upstairs: back hall by the pantry · Downstairs: storage room off the kitchen, right around the corner", "furnaceFilter": "16x25x1", "fridgeCoils": "Upstairs: front of fridge · Downstairs: front of fridge", "waterSoftener": "In the mechanical room", "shutoffs": "Main water: mech room by the water softener. Main gas: mech room on the furnace. Outside water: one in mech room (labeled) + one storage room, east wall, next to kitchen (labeled)", "knives": "Second drawer down next to the dishwasher", "medLock": "Key access", "atticAccess": "Attic access: east bedroom"}'::jsonb,
 '[["Paint","Pantry in the hallway to the garage; mech room bottom of wire shelf. CALL SUSIE BEFORE PAINTING."],["MTX cabinet","Garage"],["Breaker box","Mechanical room"],["Van key","Entryway by the garage, in the closet with the van bag"],["Outdoor spigots","North & east sides of house"],["Smokes/CO status","Replacement needed — smokes 3/28 (1 @ 3/27); CO''s 2/30, mech room 3/28"]]'::jsonb),
('16th Avenue',
 '{"waterSoftener": true, "airExchanger": true, "roofCoils": true, "sumpPump": false, "garbageDisposal": false, "generator": false}'::jsonb,
 '{"fridgeCoils": "Roof coils in garage by fuse box", "furnaceFilter": "16x25x4", "waterSoftener": "In the mechanical room — back left corner as you enter", "shutoffs": "Main water: mech room, far right corner. Main gas: mech room, closest left corner. Outside water: one above water main in mech room; one in kitchen suspended ceiling under same panel as heat vent (access through small panel next to it, toward cabinet)", "knives": "Top drawer to the left of the stove", "medLock": "Magnetic key", "dryerVents": "See house info"}'::jsonb,
 '[["Mechanical room","Located in the RS apartment"],["MTX cabinet","Back right corner of the garage"],["Breaker box","In garage"],["Air exchanger","Mech room, far right corner as you enter"],["Furnace humidifier","Yes"],["Roof anchors","This home has roof anchors"],["Generator","Removed — moved to another house"]]'::jsonb),
('140th Lane West',
 '{"waterSoftener": true, "airExchanger": false, "roofCoils": false, "garbageDisposal": false}'::jsonb,
 '{"fireExtinguishers": "Upstairs: kitchen, on the wall above the garbage cans · Downstairs: kitchen, on wall by office", "furnaceFilter": "20x25x4", "fridgeCoils": "Upstairs: front of the fridge · Downstairs: back of the fridge", "waterSoftener": "Yes", "shutoffs": "Main water: mech room by utility sink. Main gas: next to / on furnace in basement. Outside water: both in mech room — one behind the furnace, one by laundry area", "knives": "On the counter", "medLock": "2 locks, 1 keypad. Stealth lock in kitchen (code in local codes file)", "atticAccess": "Attic access: at the end of the hall by the rooms", "dryerVents": "One by the back garage door; the other near the gas meter on right side"}'::jsonb,
 '[["Paint","Shelves in mechanical room — do NOT store paint in residential area of the house"],["MTX cabinet","Garage"],["Electrical","Both lower level: one in mechanical room, one in bedroom on west side of house"],["Van key","In the drawer by the garbage cans"],["Roof coils","None — ensure there is a roof rake"],["Smokes/CO status","Resident smokes rpl. 12/26; CO rpl. 12/28 & 8/31. RS smokes various dates, rpl. all by 10/28; CO''s 3/30"]]'::jsonb),
('92nd Crescent',
 '{"waterSoftener": true, "airExchanger": true, "sumpPump": false, "garbageDisposal": true}'::jsonb,
 '{"fireExtinguishers": "Downstairs: kitchen, far right cabinet; one in the van · Upstairs: one under the sink, one in laundry room", "furnaceFilter": "16x25x4", "fridgeCoils": "See house info", "waterSoftener": "In the laundry closet — use ONLY Morton System Saver II pellets", "shutoffs": "Main gas and water: mechanical room. Outside water: both in mech room above the water heater", "knives": "On the counter", "medLock": "Digi Lock-C (code in local codes file)", "atticAccess": "Attic access: in the live-in apt, in the laundry room", "dryerVents": "Upstairs: back of the house by patio · Downstairs: by front door"}'::jsonb,
 '[["MTX cabinet","Left wall of the garage"],["Garbage disposal","Upstairs only"],["Fire stops","Yes — both upstairs and downstairs"],["Smokes/CO status","Both levels — rpl. all by 7/2028 (several exp. dates currently); CO2''s rpl. 3/2030"]]'::jsonb),
('Amble',
 '{"waterSoftener": false, "airExchanger": true, "roofCoils": true, "sumpPump": false, "generator": false, "garbageDisposal": true}'::jsonb,
 '{"fireExtinguishers": "Under sinks and in laundry rooms up and down; and in the van", "furnaceFilter": "90-day 20x25x4 — replace once every 90 days", "waterSoftener": "None — this house does not have a water softener", "shutoffs": "Main water: utility room. Main gas: utility room, next to the furnace. Exterior: back-of-house shutoff in cabinet under Resident-level kitchen sink; the faucet by the A/C is in the utility room ceiling at the back", "knives": "Right of sink — second upper cabinet", "atticAccess": "Attic access: ceiling of storage room next to utility room (garage light turns on attic light)", "dryerVents": "Downstairs: east side of house · Upstairs: back of house, middle vent next to porch (not under it); tall ladder needed"}'::jsonb,
 '[["Paint","Upstairs in the laundry room (most paint currently stored in the heated garage, 7/2022)"],["MTX cabinet","Garage, north wall by where the car parks"],["Electrical box","In the garage"],["Gas meter","East side of the house"],["Van key","On a hook by garage door"],["Roof coils","Switch on west wall of garage, just above the MTX cabinet"],["Roof anchors","Yes"],["Shed","Yes (no lock needed)"],["Garbage disposal","Upstairs yes / downstairs no"],["Air exchanger","Yes — clean pre-filters every 90 days; wash core filter each spring and fall"]]'::jsonb),
('Barclay',
 '{}'::jsonb,
 '{"furnaceFilter": "16x25x4 — Honeywell brand only", "shutoffs": "Main water: furnace room. Main gas: furnace room. Exterior: utility room, both above/behind the water heater against the wall", "medLock": "Digilock (code in local codes file)", "dryerVents": "Residents: above patio door"}'::jsonb,
 '[["Paint","Downstairs in the office-area shelving"],["Electrical box","On garage wall"]]'::jsonb),
('Bicentennial',
 '{"waterSoftener": true, "airExchanger": false, "roofCoils": true, "sumpPump": true, "generator": true, "garbageDisposal": false}'::jsonb,
 '{"fireExtinguishers": "(3) Van · west kitchen wall upstairs · under sink in basement apartment", "waterSoftener": "Yes", "shutoffs": "Main water: utility room, in front of the wash tub (kind of low). Main gas: attached to furnace. Exterior: front — utility room above sump pump; back — utility room back corner", "knives": "Cabinet above microwave", "atticAccess": "Attic access: in the hallway"}'::jsonb,
 '[["Paint","In the closet at the end of the hallway"],["MTX cabinet","Garage, along the east wall by the generator"],["Electrical box","Garage"],["Utility room","Basement apartment — through the door on the right in the kitchen"],["Gas meter","West front corner of house"],["Van key","Cabinet just left of the sun room door, next to the kitchen"],["Grounding rod","Right of the big garage door in the landscaping rock (as you look at the house); also 2ft left of the front outside faucet, 3ft out from house"],["Emergency lanterns","Garage, in a tote along the east wall by the MTX cabinet"],["Roof coils","Switch in garage by side door"],["Roof anchors","Yes"],["Shed","Yes (no lock needed)"],["Sump pump","Utility room — sealed for radon"],["Air exchanger","None"],["Dryer vent","Upstairs: just right of the front step"]]'::jsonb),
('Boutwell',
 '{"waterSoftener": false, "airExchanger": true, "roofCoils": true, "generator": true, "garbageDisposal": true}'::jsonb,
 '{"fireExtinguishers": "(3) Van · upstairs under the sink · downstairs under the sink", "furnaceFilter": "90-day filter", "waterSoftener": "None", "shutoffs": "Main gas and water: furnace room. Exterior: both in utility room — one in the middle of the ceiling, one along the left wall behind the air-exchanger vent tubing (11/2021: one may have moved; both may be along the left wall). Right above a GFI outlet and power strip — cover/protect them when draining, the pipe sprays", "knives": "On the counter", "medLock": "Magnetic locks", "atticAccess": "Attic access: back left bedroom", "dryerVents": "Only one in use — back side of the roof"}'::jsonb,
 '[["Paint","MTX cabinet outside the utility room on the RS level"],["MTX cabinet","Garage"],["Electrical box","Garage"],["Generator","General GP 15000e"],["Gas meter","North side of the house by the air conditioner"],["Van key","Pantry right of the stove (pantry key in small drawer right of the stove); also med cabinet pantry right of the stove (cabinet key in small drawer right of the fridge)"],["Roof coils","Switch / GFI is under the breaker box in the garage"],["Roof anchors","None"],["Shed","None"],["Sump pump","Asleep/night room on the lower level"],["Garbage disposal","Upstairs none / downstairs yes"],["Air exchanger","Yes — under the steps in the office"]]'::jsonb),
('Brooks',
 '{"waterSoftener": false, "airExchanger": false, "roofCoils": true, "sumpPump": false, "generator": false, "garbageDisposal": true}'::jsonb,
 '{"fireExtinguishers": "(4) locations", "furnaceFilter": "20x25x4", "waterSoftener": "None", "shutoffs": "Main water: mechanical room, straight ahead as you walk through the door. Main gas: mechanical room, behind the water heater and furnace. Exterior: front shutoff under the access panel in the RS bathroom ceiling; back shutoff in the RS laundry above the washer", "knives": "Kitchen counter", "atticAccess": "Attic access: see house info", "dryerVents": "Only one in use — under the deck, not accessible; can only be cleaned from the inside"}'::jsonb,
 '[["Paint","Laundry room, north wall"],["MTX cabinet","Garage"],["Gas meter","Back of the house behind the garage"],["Van key","Inside the left door of the black cabinet just left of the office desk"],["Grounding rod","Just left of the garage door in the rocks, about a foot out from the garage"],["Roof coils","In laundry room"],["Roof anchors","Yes"],["A/C unit","Behind the garage"],["Furnace humidifier","Yes"],["Garbage disposal","Upstairs yes / downstairs no"]]'::jsonb)
on conflict (name) do nothing;
