-- ----------------------------------------------------------------------------
-- 0005_more_houses.sql — 18 more houses (batch of 2026-07-10), plus two fixes
-- to rows applied earlier: Cummings (shed combination scrubbed — codes live
-- only in house-codes.local.js) and Ilex (garage-key line added).
--
-- Generated from route-checklist/house-data.js. Door/entry codes are NEVER
-- stored here (public repo).
--
-- Apply by hand in the Supabase dashboard SQL Editor. Safe to re-run:
-- inserts skip houses already present; updates are idempotent.
-- ----------------------------------------------------------------------------
insert into public.houses (name, equipment, notes, info) values
('Alta Vista',
 '{"waterSoftener":false,"airExchanger":false,"sumpPump":true,"generator":true,"garbageDisposal":false}'::jsonb,
 '{"fireExtinguishers":"(4) Cabinet next to meds in dining room · hallway cabinet to resident rooms · laundry room · mudroom (next to garage)","furnaceFilter":"Honeywell 16x25x4 — three: one in mechanical room, one in garage, one in mudroom off of garage (downstairs apartment)","shutoffs":"Main water: mechanical room off the basement apartment. Main water & gas: west bedroom of the basement apt. Main gas: outside the patio access for the basement apartment. Outside water: front — lower-level mudroom just off the garage; back — north-side utility room, in the ceiling straight up about 3 ft past the door entrance (it seems to turn on a spigot in the yard too — go back in the yard and check)","knives":"Lazy susan in kitchen","medLock":"Keypad med lock + locked kitchen drawer (codes in local codes file). The IEI isn''t in use anymore","atticAccess":"Attic access: 2nd bedroom","dryerVents":"One — northwest corner of house"}'::jsonb,
 '[["Paint","Garage"],["MTX cabinet","Garage"],["Van key","In the van backpack just inside the office door on the right, in the side pocket"],["Shed key","On the cabinet door on the west wall across from the kitchen sink; also a key hanging in the MTX cabinet"],["Roof anchors","Yes"],["Sump pumps","Two: patio area outside on the south side; main mechanical room, northwest corner"],["Generator","Yes — stationed in the garage"],["Gas meter","South side of the house"],["Electric/fuse boxes","1st in maintenance room, lower level below the living room; 2nd in the garage"],["Furnace humidifier","Yes"],["A/C units","Two — the big one at the back of the house, a smaller one in front"],["Garbage disposal","Upstairs no / downstairs no"]]'::jsonb),
('Jennifer Court',
 '{"waterSoftener":true,"airExchanger":false,"roofCoils":true,"sumpPump":true,"generator":false,"garbageDisposal":true}'::jsonb,
 '{"fireExtinguishers":"(4) Normal and grease under upstairs sink · under live-in sink · van","furnaceFilter":"20x25x4","waterSoftener":"Downstairs office","shutoffs":"Main water: office/utility room. Main gas: office/utility room. Outside water: front and back shutoffs next to each other on the ceiling above the wash tub in the downstairs furnace room","knives":"Block by stove","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: two — one by upstairs bathroom near front door, one in garage","dryerVents":"(2) Between addition and house (south) · near front door railing"}'::jsonb,
 '[["Paint","Office"],["MTX cabinet","Garage"],["Van key","Van bag in the closet by the front door; spare stored in office — small drawer on upper left of desk"],["Utility room","Downstairs office outside of the live-in apt — no apt entrance required"],["Sump pump","Bottom of stairs"],["Roof coils","Breaker box, fuse 11 (possibly #21 — 10/2023)"],["Electrical boxes","Two: one in garage, one in live-in apt by stairs"],["Furnace humidifier","None"],["Garbage disposal","Upstairs yes / downstairs not operational"],["Hose reel","10/2023: the back-yard hose reel broke — need a new one. RS asked that the hose not be stored in the garage without the reel, so for this winter it is under the deck. The black hose connects the spigot to the other one next to the A/C compressor (one hose for each side)"]]'::jsonb),
('Oakwood',
 '{"waterSoftener":true,"airExchanger":false,"sumpPump":false,"generator":false,"garbageDisposal":true}'::jsonb,
 '{"fireExtinguishers":"(4) Van · Upstairs: under sink, laundry · Downstairs: (not filled in on the sheet)","furnaceFilter":"16x25x1","waterSoftener":"Utility room","shutoffs":"Main water: storage room. Main gas: furnace room — look up. Outside water: 1) storage room near wall; 2) behind panel in washer room (next to utility room)","atticAccess":"Attic access: two — 1st bedroom on the left, and the garage","dryerVents":"Just one hooked up — at the back of the house by the ramp"}'::jsonb,
 '[["Paint","Office"],["MTX cabinet","Garage"],["Van key","On hook by the front door"],["Shed","Yes (no lock needed)"],["Roof anchors","Yes"],["Grounding rod","North east corner"],["Gas meter","South west corner"],["Electrical","Back bedroom"],["Furnace humidifier","Yes"],["Garbage disposal","Upstairs yes / downstairs no"]]'::jsonb),
('Regent',
 '{"waterSoftener":true,"airExchanger":true,"sumpPump":true}'::jsonb,
 '{"fireExtinguishers":"Upstairs: closet in dining room · Downstairs: in the cabinet under the island","furnaceFilter":"20x25x4 — Honeywell brand only","waterSoftener":"In the mechanical room","shutoffs":"Main water: mech room by the water heaters. Main gas: mech room by the furnace. Outside water: left side of house — under the RS kitchen sink; right side — mech room above the laundry tub","knives":"Little drawer to the right of the dishwasher","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: at the end of the hallway","dryerVents":"Upstairs: on the south wall, under the ramp to the deck · Downstairs: north wall"}'::jsonb,
 '[["Paint","Some upstairs in the closet next to the laundry; most of it down in the mechanical room"],["MTX cabinet","Garage, in the northwest corner"],["Sump pump","Closet under the stairs, room behind kitchen"],["Air exchanger","In the mechanical room above the washer and dryer"],["Garage keypad","Replaced 06/24/2026 (code in local codes file)"],["Smokes/CO status","Resident — smokes: HW rpl. 9/2027, battery rpl. 6/2031; CO rpl. 2/2030. RS level — smokes 4x rpl. 8/27; CO 2/30 & 4/26"]]'::jsonb),
('Riverdale',
 '{"waterSoftener":true,"airExchanger":false,"roofCoils":true,"sumpPump":true,"generator":false,"garbageDisposal":false}'::jsonb,
 '{"fireExtinguishers":"(6) Van · Upstairs: kitchen (hanging on the wall), laundry (on the wall to the left) · Downstairs: under kitchen sink, closet in the second living room (just right of laundry room) · 1 in the garage","furnaceFilter":"90-day 20x25x4","waterSoftener":"Yes","shutoffs":"Main water: west wall of the RS living room, under a panel. Main gas: at the meter. Outside water: RS level — one above the softener, one in the storage room above the laundry tub","knives":"On the counter","atticAccess":"Attic access: hallway","dryerVents":"Both on the south side. Right of the faucet in the corner = resident dryer vent; left of the faucet = basement apartment"}'::jsonb,
 '[["Paint","Two locations: resident-level paint in the hall closet at the bottom; RS-level paint down in the RS storage room by the work bench"],["MTX cabinet","In the garage by the door going into the house"],["Van key","In the office, in the house mail bin"],["Shed","Yes (no lock needed)"],["Roof coils","Switch near one of the electrical boxes: east wall of the RS storage room"],["Roof anchors","Yes"],["Sump pumps","Two: storage room off the hall in the RS apartment (across from the laundry room, back in the corner); window well on the south side of the house"],["Generator","Riverdale no longer has a generator"],["Grounding rod","4.5 feet right (south) of the garage door and 1 foot out from the front of the house"],["Electrical boxes","Two: RS storage room, east wall; utility room in the RS apartment"],["Furnace humidifier","None"],["Smokes/CO status","Resident — smokes 7/29, 8/29, 9/31, many other dates; CO 6/28, 3/30"]]'::jsonb),
('Robin Ave',
 '{"waterSoftener":true,"airExchanger":false,"roofCoils":true,"sumpPump":false,"garbageDisposal":true}'::jsonb,
 '{"fireExtinguishers":"Upstairs: kitchen and hallway · In the van · Downstairs: under sink and furnace room","furnaceFilter":"16x25x4 — Honeywell","waterSoftener":"Takes the softener pellets — needs to be kept full of salt to the water line","shutoffs":"Main water: RS apartment utility room, on the far west wall. Outside water: one in mech room, left of washer; one in the bedroom on the left, outside of the closet, in the ceiling next to the wall","knives":"Top left drawer, left of the dishwasher. The key for the drawer is in the med cabinet (med combo in local codes file)","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: above washer and dryer","dryerVents":"Upstairs: vented through the roof · Downstairs: vent comes out on the front ramp"}'::jsonb,
 '[["Paint","In the right front hallway closet across from the med closet"],["MTX cabinet","None — a few maintenance items in the office closet, a cabinet in the med closet, and with the paint storage"],["Van key","Hanging on the wall in the white box with drawers in the living room by the front door"],["Roof coils","Switch in apt utility room, left of dryer"],["Roof anchors","Yes"],["Master key","None needed — ICF houses do not need the resident bedroom doors to have the kwik-set doorknobs"],["Gas meter","South side of the house at the front corner"],["Electrical box","RS apartment southwest bedroom (breakers are horribly labeled)"],["Furnace humidifier","None"],["Petty cash box","In med cabinet"],["Garbage disposal","Upstairs no / downstairs yes"]]'::jsonb),
('Robin Court',
 '{"waterSoftener":true,"airExchanger":false,"roofCoils":true,"sumpPump":true,"generator":true}'::jsonb,
 '{"furnaceFilter":"Normal 16x25x4","waterSoftener":"Downstairs hallway closet next to the furnace/heater closet","shutoffs":"Main water: back bedroom closet. Outside faucet shutoffs: one above the laundry tub on the RS level; one in the master bedroom closet, in the ceiling, left side","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: end of hallway, in front of small bathroom"}'::jsonb,
 '[["Van key","Closet by front door, hanging on the inside wall"],["Roof coils","Switch next to the electric box, in the first bedroom around the corner"],["Roof anchors","Yes"],["Electric box","First bedroom around the corner"],["Sump pumps","Four: small closet in the small bedroom in the RS apt; bathroom closet in the RS bathroom; two outside — one under the steps from the RS patio, one near the mound on the southwest corner of the property"],["Generator","Yes"],["Furnace humidifier","None"],["Air exchanger","None"]]'::jsonb),
('Sherwood Place',
 '{"waterSoftener":true,"airExchanger":true,"sumpPump":false,"generator":false}'::jsonb,
 '{"fireExtinguishers":"One to the left of downstairs sink · one under the upstairs sink · one mounted on the garage wall · one in the house van","furnaceFilter":"20x25x4 — should be changed every 90 days by the live-in or RS","waterSoftener":"In furnace room","shutoffs":"Main water: furnace room, left side wall, down low. Main gas: furnace room, right side, attached to furnace duct work. Outside faucet shutoffs: both on the back wall of the furnace room, above the water softener","knives":"Knife block on the kitchen counter; also check the drawer to the left of the oven","medLock":"Same style as the apt door locks (code in local codes file)","atticAccess":"Attic access: upstairs laundry room — will need the 6 ft ladder","dryerVents":"On the back of the house, up high — will need a stepladder, or access them from the deck stairs"}'::jsonb,
 '[["Paint","Front closet — the closet to the left of the door into the garage"],["Furnace room","Door to the right of the door into the garage (immediately to your left walking into the house)"],["Electrical box","In the garage above the MTX cabinet"],["GFI","Both Resident-level bathrooms are on the same GFI, linked to the Master Bathroom on the RS level where the reset switch is"],["Roof anchors","None"],["Air exchanger","Mounted on back wall of furnace room"],["Smokes/CO status","Resident level — 3x CO rpl. 4/27, 6x smokes rpl. 12/27 (to sync dates), all wired. RS area — 1x CO rpl. 2/30, 4x smokes rpl. 12/27 (same as upstairs)"]]'::jsonb),
('Skycroft',
 '{"waterSoftener":true,"airExchanger":false,"sumpPump":false,"generator":false,"garbageDisposal":true}'::jsonb,
 '{"fireExtinguishers":"(4) Garage, laundry, van, and under sink","furnaceFilter":"90-day 20x25x4 — maintenance changes it on the house visit","waterSoftener":"Yes","shutoffs":"Main water: in the storeroom down the hallway past the laundry room and furnace room. Outside water: rear spigot — master bedroom closet ceiling; front spigot — storage area at the front of the house, in the ceiling next to the main shutoff","knives":"On the counter","medLock":"Med cabinet keypad (code in local codes file)","atticAccess":"Attic access: in the med closet in the hallway by the washer/dryer — 2 shelves to stand on plus a small ladder to get up","dryerVents":"Both on the north side of the house"}'::jsonb,
 '[["Paint","At the end of the long storage closet downstairs"],["MTX cabinet","Garage"],["Van key","Top cabinets to the right of the sink"],["Shed","Yes (no lock needed)"],["Roof anchors","Yes"],["House code","None"],["Electrical box","Office downstairs in the RS''s apartment"],["Garbage disposal","Upstairs no / downstairs yes"]]'::jsonb),
('Sunbury',
 '{"sumpPump":true,"airExchanger":true}'::jsonb,
 '{"furnaceFilter":"16x25x4 90-day — needs to be changed every 3 months","shutoffs":"Main water: RS apartment utility room (in the bathroom). Main gas: RS apartment utility room, in the bathroom next to the furnace. Outside water: front faucet shutoff under the kitchen sink on the resident level; back faucet shutoff in the RS apartment utility room, on the ceiling above the water softener"}'::jsonb,
 '[["Sump pump","In the bedroom off the kitchen in the RS apartment"],["Electrical box","On the far wall of the garage"],["Air exchanger","In the utility room in the RS bathroom"]]'::jsonb),
('Tiller Lane',
 '{"waterSoftener":false}'::jsonb,
 '{"fireExtinguishers":"Garage, under kitchen sink, van, downstairs apartment, and laundry room","furnaceFilter":"20x25x4","waterSoftener":"N/A","shutoffs":"Main water: southwest corner of the basement apartment kitchen, behind the lazy susan. Main gas: north end of the basement apartment kitchen above the washer/dryer (a washer/dryer may not be hooked up — you''ll see the duct and pipe ready for one). Outside water: front faucet shutoff in the storage room off the mech room; back faucet shutoff in the RS apartment small bedroom under the ceiling access panel","medLock":"Medicine closet keypad (code in local codes file)","atticAccess":"Attic access: western hallway ceiling","dryerVents":"On the front of the house at the end of the ramp"}'::jsonb,
 '[["Paint","Down in the storage/laundry room in a closet"],["Electrical panel","In garage"]]'::jsonb),
('Toledo',
 '{"waterSoftener":false,"roofCoils":true}'::jsonb,
 '{"fireExtinguishers":"(3) Upstairs: laundry closet · Downstairs: under kitchen sink · One in the van","furnaceFilter":"Two furnaces — both 20x25 (a 1-inch and a 4-inch filter)","fridgeCoils":"Upstairs: front of fridge · Downstairs: back of fridge","waterSoftener":"None","shutoffs":"Main water: mechanical room. Main gas: at the meter. Outside water: front — RS laundry room behind the furnace, up in the ceiling; back — mech room above the water heater","knives":"Above the pantry — most are serrated","medLock":"Stealth lock — 1 keypad, 3 locks (code in local codes file)","atticAccess":"Attic access: in the closet of the back bedroom on the right","dryerVents":"Upstairs: on the back of the house · Downstairs: on the front of the house"}'::jsonb,
 '[["Paint","In the closet at the bottom of the stairs by the RS apartment"],["Roof coils","Switch in garage, by the trash"],["Furnace humidifier","In mechanical room on the right"],["Grounding rod","On the southeast corner of the garage"],["Breaker box","In left bedroom in live-in apartment"],["Smokes/CO status","Resident — smokes 1/35 hallway, 1/31, 2@3/30, 2@2/32 battery; CO 2/30. RS — smokes 4/29, 2x 1/31, 2/26, 10/31 battery; CO 2/30 & 4/30"]]'::jsonb),
('Trenton Lane',
 '{"sumpPump":true,"roofCoils":false,"generator":false}'::jsonb,
 '{"furnaceFilter":"Two furnaces: 16x25x1 fiberglass + 20x25x4 Honeywell brand only, change monthly (one sheet row lists ''6x25x4'' — verify size on site)","shutoffs":"Main water: by the water heater. Main gas: in front of the furnace. Outside water: both are in the next room to the right of the water heaters, connected to the water main entry, about 5 feet off the ground","dryerVents":"Resident dryer vents through the roof"}'::jsonb,
 '[["Thermostats","One on each level"],["Sump pump","Laundry closet downstairs"],["Furnace","In the RS apartment"],["Roof coils","None — ensure there is roof rakes"],["Electrical","In the garage"],["Emergency light","In mechanical room"],["Driveway","Asphalt"],["A/C unit","In back of house"],["CO detectors","Kidde — two in the hall on Resident level, one in hall on RS level"]]'::jsonb),
('Valders',
 '{"waterSoftener":false,"airExchanger":false,"roofCoils":true,"garbageDisposal":false,"frontLoadWashers":true}'::jsonb,
 '{"fireExtinguishers":"Resident level: above kitchen sink on cabinet · Van: on passenger seat · RS level: under kitchen sink","furnaceFilter":"90-day 20x25x4","waterSoftener":"None","shutoffs":"Main water: in the utility room on the right half of it. Main gas: on the furnace. Outside water: 2 shutoffs in the mech room by the storage shelves — one is above the main water shutoff","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: in the garage","dryerVents":"Upstairs: right outside the garage door · Downstairs: right outside the garage door"}'::jsonb,
 '[["Roof coils","Switch located by breaker box in mech room"],["Breaker boxes","One in the furnace room downstairs; the other in the RS apartment at the end of the hall, in the room on the right"],["Furnace humidifier","None"],["Front-load washer","Downstairs only"],["Smokes/CO status","CO''s all levels — replace 2/2030. Smokes — Resident level: 1 rpl. 2027 hallway, remaining 4/2034; RS level: rpl. all 1/28"]]'::jsonb),
('Oregon Brooklyn Park (OBP)',
 '{"waterSoftener":true,"airExchanger":true,"garbageDisposal":true,"frontLoadWashers":true}'::jsonb,
 '{"fireExtinguishers":"Upstairs: in the kitchen by the cabinet; also one in the garage · Downstairs: under the kitchen sink","furnaceFilter":"20x25x4 — Honeywell brand only","waterSoftener":"Basement mech. room","shutoffs":"Main water: mechanical room, between the furnace and water heater. Main gas: mechanical room, on the wall by the furnace. Outside water: both shutoffs left of the furnace","knives":"In the cabinet to the right of the stove","medLock":"Stealth locks (code in local codes file)","atticAccess":"Attic access: at the end of the hallway","dryerVents":"Upstairs: on the roof · Downstairs: on the east end of the house"}'::jsonb,
 '[["Paint","Basement — back room closet"],["MTX cabinet","Garage"],["Mechanical room","RS apt, first door on the right"],["Grounding rod","On the front of the home, about 2 feet to the left of the step"],["Power panel","In the storage room off the kitchen, on the far wall"],["Roof anchors","Yes"],["Air exchanger","In the mech. room"],["A/C unit","On the east side of the house"],["Front-load washer","Resident level"],["Fire stops","Replace 2029"],["Garbage disposal","Downstairs only"],["Smokes/CO status","Smokes — 4 up, 4 down (various dates), replace all by 9/27. CO''s — 2 up, rpl. 3/30, 2/31; RS level rpl. 11/30"]]'::jsonb),
('Redwood',
 '{"waterSoftener":true,"airExchanger":false,"roofCoils":true,"sumpPump":false,"garbageDisposal":true}'::jsonb,
 '{"fireExtinguishers":"(6) Van, kitchen, front closet, dryer closet upstairs, sleep room, under sink downstairs","furnaceFilter":"14x25x1 30-day — change monthly","waterSoftener":"Yes","shutoffs":"Main water: RS apartment bedroom next to the utility room. Outside faucet shutoffs: by the main shutoff (inside closet by the patio door); also inside the wood cabinet in the spare room — the shutoff is up high inside the wall cabinet. RS level: one in the pantry closet in the addition, one in the small bedroom closet with face frame, in the ceiling","knives":"The lazy susan","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: one right above the garage entrance door (accessible), and one in the laundry closet that is super hard to get to — so use the garage access","dryerVents":"Basement apartment: comes out at the front of the house under the kitchen window · Upstairs: on the north side of the house, up high"}'::jsonb,
 '[["Paint","In a metal cabinet down in the utility room"],["MTX cabinet","In the garage along the back wall"],["Van key","Kitchen cabinet closest to dining table"],["Shed","Yes (no lock needed)"],["Roof coils","The switch is by the garage door"],["Roof anchors","Yes"],["Grounding rod","In the landscaping to the south of the big garage door, between the sidewalk and garage"],["Electrical boxes","RS apartment first living room along the west wall; another in the closet off the addition in the RS apartment"],["Furnace humidifier","None"],["A/C units","(5) 3 outside on the north side — 1 big one and 2 smaller ones down the hill; 2 inside — one in the living room downstairs, one in the sunroom upstairs"],["Garbage disposal","Upstairs yes / downstairs no"]]'::jsonb),
('Oregon Golden Valley (OGV)',
 '{"waterSoftener":false,"airExchanger":false,"generator":true,"garbageDisposal":false}'::jsonb,
 '{"fireExtinguishers":"Resident level: laundry closet and in kitchen next to fridge · RS level: under kitchen sink, van, garage","furnaceFilter":"20x25x4","fridgeCoils":"Upstairs: front/back · Downstairs: front/back","waterSoftener":"None","shutoffs":"Main water: in the laundry room. Main gas: at meter. Outside water: RS level — the front faucet valve is in the back bedroom behind the ceiling access panel that is close to the closet; the back faucet valve is in the laundry room above the door","knives":"Med cabinet","medLock":"Stealth lock (code in local codes file)","atticAccess":"Attic access: little storage closet in office area","dryerVents":"Upstairs: roof · Downstairs: on north side of the house"}'::jsonb,
 '[["MTX cabinet","Garage"],["Van key","Drawer right by the entryway to the living room"],["Generator","Yes — in the garage"],["Fire stops","Magnet type — rpl''d 8/23"],["Smokes/CO status","Resident — rpl. smokes 2/27 & 6/28; rpl. CO 3/30. RS — various dates, replace all 2/28; CO rpl. 8/30"]]'::jsonb),
('Riverton',
 '{"waterSoftener":true,"airExchanger":false,"sumpPump":false,"generator":false,"garbageDisposal":false}'::jsonb,
 '{"fireExtinguishers":"(3) One in the van · Upstairs: in the cabinet right of the fridge · Downstairs: in the cabinet just right of the dishwasher","furnaceFilter":"20x25x4 — Honeywell brand only","waterSoftener":"Yes","shutoffs":"Main water: RS apartment, in the closet off the kitchen, right next to the front outside water shutoff. Main gas: RS apartment utility room, in front of the furnace. Outside water: backyard shutoff behind the cover box in the ceiling just above the entrance to the utility room; front yard in the pantry left of the dishwasher — both in the basement apt","knives":"In the far right pantry to the right of the fridge (this is also the med cabinet)","atticAccess":"Attic access: in the hallway upstairs","dryerVents":"Upstairs: super short run straight out on the west side of the house · Downstairs: (not filled in on the sheet)"}'::jsonb,
 '[["Paint","Back closet in RS level office"],["MTX cabinet","In the garage next to the door that goes into the house"],["Van key","Coat closet by the front door (box code in local codes file)"],["Spare key","See local codes file"],["Shed","None"],["Roof anchors","None"],["Grounding rod","Right corner of the house, about a foot out from the house going west and about 6 inches set in"],["Electrical box","In the RS apartment in the back bedroom at the end of the hall"],["Furnace humidifier","None"],["Garbage disposal","Upstairs none / downstairs none"]]'::jsonb)
on conflict (name) do nothing;

update public.houses set info = '[["Paint","Utility room downstairs (not RS apt), in a wall cabinet"],["MTX cabinet","Garage, by the big door"],["Electrical box","RS apartment small office room, to the left as you enter"],["Van key","Cabinet right of clock"],["Shed","Combination in local codes file"],["Roof anchors","Yes"]]'::jsonb
 where name = 'Cummings';

update public.houses set info = '[["Paint","Closet cabinet to the right of the desk in the living-room area"],["MTX cabinet","Garage, along the west wall"],["Electrical box","RS bedroom"],["Van key","Hangs by the front door"],["Garage key","Hanging by the front door"],["Grounding rod","2ft left of the outside faucet, 3ft out from the house"],["Gas meter","Front north side of house"],["Emergency lanterns","Garage, by the MTX cabinet"],["Roof coils","By breaker box, in main bedroom in RS apt"],["Roof anchors","Yes"],["Utility room","Downstairs — through the basement apartment, door right of the kitchen fridge"],["Garbage disposal","Upstairs yes / downstairs no"],["Washing machines","Up: front-load / Down: top-load"],["Smokes/CO status","Resident: smokes battery 8/2019, 2×9/2019; HW 2×11/2019, 9/23; CO''s 2×1/30. RS: change all smokes by 8/2029 (2 battery, 1 hardwire)"]]'::jsonb
 where name = 'Ilex';
